// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomOi.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MomOi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.BabyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string[]>("Allergies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergies");

                    b.Property<string>("BabyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baby_name");

                    b.Property<float?>("CurrentHeightCm")
                        .HasColumnType("real")
                        .HasColumnName("current_height_cm");

                    b.Property<float?>("CurrentWeightKg")
                        .HasColumnType("real")
                        .HasColumnName("current_weight_kg");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string[]>("FoodHistory")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("food_history");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_baby_profiles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_baby_profiles_user_id");

                    b.ToTable("baby_profiles", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("ChatSessionId")
                        .HasDatabaseName("ix_chat_messages_chat_session_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_sessions_user_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.CriticalAlertLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<string>("MessageVi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_vi");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("SuggestionVi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suggestion_vi");

                    b.Property<string>("TitleVi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_vi");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_critical_alert_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_critical_alert_logs_user_id");

                    b.ToTable("critical_alert_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.CycleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Symptoms")
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.HasKey("Id")
                        .HasName("pk_cycle_logs");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_cycle_logs_profile_id");

                    b.ToTable("cycle_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.DailyMonitoringLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllergySymptomLogged")
                        .HasColumnType("boolean")
                        .HasColumnName("allergy_symptom_logged");

                    b.Property<int>("BabyFishServings")
                        .HasColumnType("integer")
                        .HasColumnName("baby_fish_servings");

                    b.Property<string>("BabyFoodTexture")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baby_food_texture");

                    b.Property<float>("BabyIronInput")
                        .HasColumnType("real")
                        .HasColumnName("baby_iron_input");

                    b.Property<int?>("BloodPressureHigh")
                        .HasColumnType("integer")
                        .HasColumnName("blood_pressure_high");

                    b.Property<int?>("BloodPressureLow")
                        .HasColumnType("integer")
                        .HasColumnName("blood_pressure_low");

                    b.Property<float?>("BloodSugar")
                        .HasColumnType("real")
                        .HasColumnName("blood_sugar");

                    b.Property<int>("ConceptionDayOfCycle")
                        .HasColumnType("integer")
                        .HasColumnName("conception_day_of_cycle");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("EpdsScore")
                        .HasColumnType("integer")
                        .HasColumnName("epds_score");

                    b.Property<bool>("HadBreakfast")
                        .HasColumnType("boolean")
                        .HasColumnName("had_breakfast");

                    b.Property<bool>("HadDinner")
                        .HasColumnType("boolean")
                        .HasColumnName("had_dinner");

                    b.Property<bool>("HadLunch")
                        .HasColumnType("boolean")
                        .HasColumnName("had_lunch");

                    b.Property<string>("MoodNote")
                        .HasColumnType("text")
                        .HasColumnName("mood_note");

                    b.Property<int?>("MoodScore")
                        .HasColumnType("integer")
                        .HasColumnName("mood_score");

                    b.Property<string>("NewFoodLogged")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_food_logged");

                    b.Property<float?>("SleepHours")
                        .HasColumnType("real")
                        .HasColumnName("sleep_hours");

                    b.Property<int?>("SleepQuality")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_quality");

                    b.Property<int>("Steps")
                        .HasColumnType("integer")
                        .HasColumnName("steps");

                    b.Property<string>("SymptomNote")
                        .HasColumnType("text")
                        .HasColumnName("symptom_note");

                    b.Property<int?>("SymptomSeverity")
                        .HasColumnType("integer")
                        .HasColumnName("symptom_severity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<float?>("WaterLiters")
                        .HasColumnType("real")
                        .HasColumnName("water_liters");

                    b.Property<float?>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_daily_monitoring_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_daily_monitoring_logs_user_id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_monitoring_logs_user_id_date");

                    b.ToTable("daily_monitoring_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.DietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DailyMealsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("daily_meals_json");

                    b.Property<string>("GeneratedFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generated_from");

                    b.Property<DateTime?>("MonitoringDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("monitoring_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int?>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.HasKey("Id")
                        .HasName("pk_diet_plans");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_diet_plans_user_id");

                    b.ToTable("diet_plans", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.EpdsAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiAnalysis")
                        .HasColumnType("text")
                        .HasColumnName("ai_analysis");

                    b.Property<int[]>("Answers")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("answers");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.HasKey("Id")
                        .HasName("pk_epds_assessments");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_epds_assessments_profile_id");

                    b.ToTable("epds_assessments", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.ExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise_type");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("StepCount")
                        .HasColumnType("integer")
                        .HasColumnName("step_count");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_exercise_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_exercise_logs_user_id");

                    b.ToTable("exercise_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.GrowthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BabyProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_profile_id");

                    b.Property<float>("HeightCm")
                        .HasColumnType("real")
                        .HasColumnName("height_cm");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<float>("WeightKg")
                        .HasColumnType("real")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_growth_records");

                    b.HasIndex("BabyProfileId")
                        .HasDatabaseName("ix_growth_records_baby_profile_id");

                    b.ToTable("growth_records", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.LifestyleAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DailyMonitoringLogId")
                        .HasColumnType("integer")
                        .HasColumnName("daily_monitoring_log_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suggestion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lifestyle_alerts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lifestyle_alerts_user_id");

                    b.ToTable("lifestyle_alerts", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.LifestyleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<float>("ExtracurricularHours")
                        .HasColumnType("real")
                        .HasColumnName("extracurricular_hours");

                    b.Property<float>("Gpa")
                        .HasColumnType("real")
                        .HasColumnName("gpa");

                    b.Property<int>("HealthScore")
                        .HasColumnType("integer")
                        .HasColumnName("health_score");

                    b.Property<string>("LifestyleProfile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lifestyle_profile");

                    b.Property<float>("PhysicalHours")
                        .HasColumnType("real")
                        .HasColumnName("physical_hours");

                    b.Property<float>("SleepHours")
                        .HasColumnType("real")
                        .HasColumnName("sleep_hours");

                    b.Property<float>("SocialHours")
                        .HasColumnType("real")
                        .HasColumnName("social_hours");

                    b.Property<string>("StressLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stress_level");

                    b.Property<float>("StudyHours")
                        .HasColumnType("real")
                        .HasColumnName("study_hours");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lifestyle_entries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lifestyle_entries_user_id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_lifestyle_entries_user_id_date");

                    b.ToTable("lifestyle_entries", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.MedicationAdherenceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("MedicationScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_medication_adherence_logs");

                    b.HasIndex("MedicationScheduleId")
                        .HasDatabaseName("ix_medication_adherence_logs_medication_schedule_id");

                    b.ToTable("medication_adherence_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.MedicationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dosage");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("MedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("med_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string[]>("Times")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("times");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_medication_schedules");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_medication_schedules_user_id");

                    b.ToTable("medication_schedules", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.MomHealthProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvgCycleLength")
                        .HasColumnType("integer")
                        .HasColumnName("avg_cycle_length");

                    b.Property<float?>("BloodSugarLevel")
                        .HasColumnType("real")
                        .HasColumnName("blood_sugar_level");

                    b.Property<float?>("Bmi")
                        .HasColumnType("real")
                        .HasColumnName("bmi");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<bool>("HasGestDiabetes")
                        .HasColumnType("boolean")
                        .HasColumnName("has_gest_diabetes");

                    b.Property<bool>("IsBreastfeeding")
                        .HasColumnType("boolean")
                        .HasColumnName("is_breastfeeding");

                    b.Property<DateTime?>("LastPeriodDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_period_date");

                    b.Property<string[]>("MedicalConditions")
                        .HasColumnType("text[]")
                        .HasColumnName("medical_conditions");

                    b.Property<int?>("PregnancyWeek")
                        .HasColumnType("integer")
                        .HasColumnName("pregnancy_week");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mom_health_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_mom_health_profiles_user_id");

                    b.ToTable("mom_health_profiles", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.NotificationAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string[]>("Channels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("channels");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_alerts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_alerts_user_id");

                    b.ToTable("notification_alerts", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.PostpartumLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BleedingStatus")
                        .HasColumnType("text")
                        .HasColumnName("bleeding_status");

                    b.Property<int>("DaysPostpartum")
                        .HasColumnType("integer")
                        .HasColumnName("days_postpartum");

                    b.Property<string>("Mood")
                        .HasColumnType("text")
                        .HasColumnName("mood");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_postpartum_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_postpartum_logs_user_id");

                    b.ToTable("postpartum_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.PregnancyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("DiastolicBp")
                        .HasColumnType("real")
                        .HasColumnName("diastolic_bp");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<float?>("SystolicBp")
                        .HasColumnType("real")
                        .HasColumnName("systolic_bp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Week")
                        .HasColumnType("integer")
                        .HasColumnName("week");

                    b.Property<float?>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_pregnancy_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pregnancy_logs_user_id");

                    b.ToTable("pregnancy_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<string>("Carbs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("carbs");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<string>("Fat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fat");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredients_json");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_saved");

                    b.Property<string>("PrepTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prep_time");

                    b.Property<string>("ProfileStage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_stage");

                    b.Property<string>("Protein")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protein");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steps_json");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recipes_user_id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Health.SymptomLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_flag");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string[]>("DietarySuggestions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("dietary_suggestions");

                    b.Property<string>("Disclaimer")
                        .HasColumnType("text")
                        .HasColumnName("disclaimer");

                    b.Property<string>("GeminiModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gemini_model");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("text")
                        .HasColumnName("image_mime_type");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("images");

                    b.Property<bool>("IsAdminReviewRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin_review_required");

                    b.Property<string>("LifestyleConnection")
                        .HasColumnType("text")
                        .HasColumnName("lifestyle_connection");

                    b.Property<string>("PossibleConditionsJson")
                        .HasColumnType("text")
                        .HasColumnName("possible_conditions_json");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("ProfileStage")
                        .HasColumnType("text")
                        .HasColumnName("profile_stage");

                    b.Property<string[]>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recommendations");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("integer")
                        .HasColumnName("severity_score");

                    b.Property<bool>("ShouldSeeDoctor")
                        .HasColumnType("boolean")
                        .HasColumnName("should_see_doctor");

                    b.Property<string>("SpecialistType")
                        .HasColumnType("text")
                        .HasColumnName("specialist_type");

                    b.Property<string>("TextDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrgencyLevel")
                        .HasColumnType("text")
                        .HasColumnName("urgency_level");

                    b.Property<string>("UrgencyReason")
                        .HasColumnType("text")
                        .HasColumnName("urgency_reason");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_symptom_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_symptom_logs_user_id");

                    b.ToTable("symptom_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateTime?>("TierExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tier_expires_at");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Nutrition.BabyFoodLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string[]>("AllergySymptoms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergy_symptoms");

                    b.Property<int>("BabyProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_profile_id");

                    b.Property<string>("IntroducedFoodName")
                        .HasColumnType("text")
                        .HasColumnName("introduced_food_name");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<string>("MealTexture")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meal_texture");

                    b.Property<bool>("NewFoodIntroduced")
                        .HasColumnType("boolean")
                        .HasColumnName("new_food_introduced");

                    b.Property<float>("TotalIronMg")
                        .HasColumnType("real")
                        .HasColumnName("total_iron_mg");

                    b.Property<int>("WeeklyFishServings")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_fish_servings");

                    b.HasKey("Id")
                        .HasName("pk_baby_food_logs");

                    b.HasIndex("BabyProfileId")
                        .HasDatabaseName("ix_baby_food_logs_baby_profile_id");

                    b.ToTable("baby_food_logs", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Nutrition.FoodAllergyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allergen");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_food_allergy_records");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_food_allergy_records_user_id");

                    b.ToTable("food_allergy_records", (string)null);
                });

            modelBuilder.Entity("MomOi.API.Models.Nutrition.MealLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Calories")
                        .HasColumnType("real")
                        .HasColumnName("calories");

                    b.Property<float>("Carbs")
                        .HasColumnType("real")
                        .HasColumnName("carbs");

                    b.Property<float>("Fat")
                        .HasColumnType("real")
                        .HasColumnName("fat");

                    b.Property<string[]>("FoodItems")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("food_items");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meal_type");

                    b.Property<float>("Protein")
                        .HasColumnType("real")
                        .HasColumnName("protein");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_meal_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_meal_logs_user_id");

                    b.ToTable("meal_logs", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MomOi.API.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MomOi.API.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("MomOi.API.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MomOi.API.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.ChatMessage", b =>
                {
                    b.HasOne("MomOi.API.Models.Health.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_sessions_chat_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.CycleLog", b =>
                {
                    b.HasOne("MomOi.API.Models.Health.MomHealthProfile", "Profile")
                        .WithMany("CycleLogs")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycle_logs_mom_health_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.EpdsAssessment", b =>
                {
                    b.HasOne("MomOi.API.Models.Health.MomHealthProfile", "Profile")
                        .WithMany("EpdsAssessments")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epds_assessments_mom_health_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.GrowthRecord", b =>
                {
                    b.HasOne("MomOi.API.Models.Health.BabyProfile", "BabyProfile")
                        .WithMany("GrowthRecords")
                        .HasForeignKey("BabyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_growth_records_baby_profiles_baby_profile_id");

                    b.Navigation("BabyProfile");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.MedicationAdherenceLog", b =>
                {
                    b.HasOne("MomOi.API.Models.Health.MedicationSchedule", "Schedule")
                        .WithMany("AdherenceLogs")
                        .HasForeignKey("MedicationScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_adherence_logs_medication_schedules_medication_s");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.MomHealthProfile", b =>
                {
                    b.HasOne("MomOi.API.Models.Identity.AppUser", "User")
                        .WithOne("HealthProfile")
                        .HasForeignKey("MomOi.API.Models.Health.MomHealthProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mom_health_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.BabyProfile", b =>
                {
                    b.Navigation("GrowthRecords");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.MedicationSchedule", b =>
                {
                    b.Navigation("AdherenceLogs");
                });

            modelBuilder.Entity("MomOi.API.Models.Health.MomHealthProfile", b =>
                {
                    b.Navigation("CycleLogs");

                    b.Navigation("EpdsAssessments");
                });

            modelBuilder.Entity("MomOi.API.Models.Identity.AppUser", b =>
                {
                    b.Navigation("HealthProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
